### ISSUE TITLE
previous next buttons

### ISSUE THREAD

**Issue by devmondo** [brantwills/Angular-Paging#1]
hi, 
great work there, 

but what about preview, next, first last buttons

thanks in advanced.

**Comment by mastermind1981** [comment]
Hi,

Great work done in your module. Is there any news concering adding next/previous label to the module?

Thanks

**Comment by brantwills** [comment]
Hey mastermind,

It depends on how you define 'next/previous' buttons 

I closed this issue with then inclusion of an attribute called `show-prev-next`

When set to `true` this triggers the arrows buttons for next/previous/first/last `<<, <, >, >>`

You can play around with this in the <b>[advanced sample on the demo page](http://brantwills.github.io/Angular-Paging/)</b>


----------


However, if you define next/previous buttons as say a pointer to some outside button on the page or having the ability to add or customize the buttons - then no that has not been implemented.

Hope that helps alittle bit - let me know if there is a specific function you're after!

**Comment by mastermind1981** [comment]
Thank you
