### ISSUE TITLE
Error: [$compile:nonassign] on pagingAction

### ISSUE THREAD

**Issue by aethawalka** [brantwills/Angular-Paging#12]
Hey, brantwills) Thanks for this awesome directive.
Could you help me?

I've added pagingAction, but somehow returns ["Error: [$compile:nonassign]"](https://docs.angularjs.org/error/$compile/nonassign?p0=1&p1=paging) when I click at some page.

My markup looks like as your exapmle code:
``` html
<paging
	...
	paging-action="DoCtrlPagingAct('Paging Clicked', page)">
</paging>
```

and scope's method:
```js
$scope.DoCtrlPagingAct = function(text, page){
    console.log(text, page);
};
```

I have 1.3 version of Angular.

**Comment by aethawalka** [comment]
I've found the leak, my fault.
Needed to assign the `page` to my $scope variable without curly braces.

Thanks again)

**Comment by brantwills** [comment]
ha yeah I'm pretty sure I do that at least once a week (:

Brings up a good point though, I'm not thrilled with how the 'page variable' is implemented - feels like there has to be a better way.. i duno - if you come across anything let me know and thanks again for checking this stuff out!
