### ISSUE TITLE
how i can dynamic change on paging size?

### ISSUE THREAD

**Issue by Claud** [brantwills/Angular-Paging#16]
Hello I get data on the number of pages from the server. But the size of the paging not changing.

**Comment by brantwills** [comment]
Hey Claud,

The paging size will update when the directive `page-size` attribute is updated.
Although updated on the server, you will want to also update the size on the client.
In my tests I did not detect any issues with the paging size not changing.

To gain a better understanding of the directive I recommend studying the [index.html](https://github.com/brantwills/Angular-Paging/blob/master/index.html) file locally.
Hopefully that may clear up the issues you are having.

Please feel free to expand on your issue if you have a chance,
I'll continue to test on my end for any issues with the page size not changing

**Comment by Claud** [comment]
I'm sorry, you're right, it's my fault.

**Comment by brantwills** [comment]
No worries at all

Thanks again for checking out the directive and let me know if you come across any other issues!
