### ISSUE TITLE
minified version

### ISSUE THREAD

**Issue by bludream** [brantwills/Angular-Paging#18]
I think you could also put a minified version here so just jump into work. and a CDN would be awesome for this very useful library.

**Comment by optyler** [comment]
Hi, 

this is a good idea, for instance, you can use https://rawgit.com/ to serve raw files from git served via MaxCDN... 

For exemple for test purposes it should be (linked on the master) : 
https://rawgit.com/brantwills/Angular-Paging/master/paging.js

And for production (tag version and minified version in the future) : 
https://rawgit.com/brantwills/Angular-Paging/v1.0.3/paging.js

**Comment by brantwills** [comment]
Sounds excellent thanks all!

I will leave this issue open until a minified version lands - I'm looking into build options for this now

I also have started looking into CDN services like https://cdnjs.com/

They, along with several others, have a pull request system to include new libraries

Until then the rawgit CDN service is free and certainly a great option for us at the moment

**Comment by brantwills** [comment]
For version 2.0.0 I've added a [distribution (dist)](https://github.com/brantwills/Angular-Paging/tree/master/dist) folder for things like CDN links to a minified version
I also included the rawgit links in the `dist/readme.md` file
Finally I included a CDN badge in the root readme file
