### ISSUE TITLE
How do you launch the tests?

### ISSUE THREAD

**Issue by optyler** [brantwills/Angular-Paging#21]
Hi,

I tryed to launch Karma tests with `karma start test/karma.conf.js`, is this the good way to do it?

**Comment by brantwills** [comment]
Hey optyler,

Yeah that is pretty much what I do except I usually `cd` into the test folder and perform `karma start`
This opens up a Chrome browser where Karma tells me it has connected

I don't think I installed any other npm stuff except karma-cli and maybe the chrome launcher? 
If I were to guess, there might be something fishy with Chrome being the browser of choice?
The `karma.config.js` offers this link to browser launchers: https://npmjs.org/browse/keyword/karma-launcher

From there I use `karma run` and the tests kick off while updating the chrome browser with any status stuff

I've successfully ran the test on windows 7 and OSX following the steps above
Let me know if you find a simpler (or more standard) method - maybe like phantomJS over Chrome?

**Comment by optyler** [comment]
Well, if you don't mind, I can a `package.json` file that can embed all required dependencies for tests. 
Test could also be run with npm with `npm test` command. 
I can add `karma-jasmine-html-reporter ` for a better reading.

**Comment by brantwills** [comment]
Yeah I'm right there with you  - I'm getting the feeling it might even be worth looking into some file restructuring -  I've been looking around and really like how [angular-formly](https://github.com/formly-js/angular-formly) is configured.

If you have time feel free to update as needed!  I'm still learning the npm side of things which has been really awesome, but might take me awhile to really understand all the configuration pieces.

**Comment by optyler** [comment]
With some `npm` stuff and `grunt tasks` we can try to do something similar, but I'm not an expert too.

About tests, I'll make some changes on a forked branch to let you see how i've made it running here. Up to you to merge the pull request ;)

**Comment by brantwills** [comment]
Alrighty! 

I've published some npm work to the **[npm branch](https://github.com/brantwills/Angular-Paging/tree/npm)** - any feedback is more than welcome!

Two changes of note:
1) Updated the module name from `brantwills.paging` to just simply `bw.paging` 
2) Placing the code into `src` and `dist` folders

Hopefully this makes things easier for minified files and doesn't break anything for anyone!
Unless something crazy happens, I plan on migrating this and tagging it with v1.0.4 within the next week

**Comment by optyler** [comment]
Seams great to me!
... And using PhantomJS + karma-spec-reporter is a better idea then mine ;-)

Maybe a "Change log" file will be helpfull for people looking for the changes between versions, sometimes, git commit review is hard to understand.
I thought about that beacause many users will have injections issues after module renaming.

**Comment by brantwills** [comment]
Oh man change log brilliant!
Thank so much for giving this a look over!!

Yeah, that is my greatest fear is the module rename - but I think it will be for the best in the long run - I feel awkward with my name in there!

**Comment by optyler** [comment]
Lol, are you affraid to be famous?! ;)

**Comment by brantwills** [comment]
bwahah noo just looking to avoid any blame :)
