### ISSUE TITLE
Support angular1.2.x? 

### ISSUE THREAD

**Issue by mizhdi** [brantwills/Angular-Paging#23]
Expression 'undefined' used with directive 'paging' is non-assignable!

**Comment by brantwills** [comment]
Yikes! Great catch Mizhdi I'll dig into this later tonight

**Comment by brantwills** [comment]
Mmm I'm unable to repeat the issue locally 

All tests and demo pages seem to work with Angular 1.2.28 and Angular Mocks 1.2.28 (I selected 1.2.28 as Angular lists that as the current stable 1.2.x version)

I've published a branch to explore this issue - let me know if you see something incorrect or if there are any additional notes or error codes you could provide!

https://github.com/brantwills/Angular-Paging/tree/iss23

**Comment by brantwills** [comment]
Closing as not repeatable - all test point to the directive working in Angular 1.2.28 - feel free to comment after closure!
