### ISSUE TITLE
Is there a way to limit the displayed numbers in pagination?

### ISSUE THREAD

**Issue by xxryan1234** [brantwills/Angular-Paging#24]
for example I have 20 pages. What I want to see first in my page is just 1-5 rather than the usual display 1-5..19 20

**Comment by xxryan1234** [comment]
something like the traditional pagination design to be more specific.

**Comment by brantwills** [comment]
Hey Ryan,

I don't quite follow what you are asking, do you have a link to an image of the traditional pagination design you are referencing?

If you are interested in just showing pages 1 through 5 and not showing the other pages, you would need to perform some simple math to calculate the correct the `total` to pass into the directive - But I get the impression you are looking for something else.

I'll keep this issue open until we can get you a solid answer and thanks for checking out the directive!

**Comment by xxryan1234** [comment]
![screenshot from 2015-09-23 12 41 52](https://cloud.githubusercontent.com/assets/5448370/10038012/8b246e4e-61f0-11e5-9c6f-8c33f6f542f5.png)

the traditional design where it shows 1-5 at first and then there is first and last button in the end. The "dots" attribute would also not be displayed.

Thanks also for the reply!

**Comment by optyler** [comment]
What append if :

the current page is 4, this will be OK? : *<*  2 3 *4* 5 6  *>*
If the last page & current is 6? : *<*  2 3 4 5 *6*

On Wed, Sep 23, 2015 at 6:44 AM, Cris Ryan Tan <notifications@github.com>
wrote:

> [image: screenshot from 2015-09-23 12 41 52]
> <https://cloud.githubusercontent.com/assets/5448370/10038012/8b246e4e-61f0-11e5-9c6f-8c33f6f542f5.png>
>
> the traditional design where it shows 1-5 at first and then there is first
> and last button in the end. The "dots" attribute would also not be
> displayed.
>
> Thanks also for the reply!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brantwills/Angular-Paging/issues/24#issuecomment-142490073>
> .
>



-- 
*Et aussi sur **facebook <http://www.facebook.com/optyler>** / **flickr*
<http://www.flickr.com/photos/optyler/>* / **Google+*
<https://plus.google.com/u/0/109694994098307678378/about> / *doyoubuzz*
<http://www.doyoubuzz.com/patrick-ferreira>

**Comment by xxryan1234** [comment]
:+1:  @optyler

**Comment by brantwills** [comment]
Thanks Ryan, very helpful, I think I see what you are after.

To answer your question, the dots are always visible unless there are to few pages to display.
I've included a sample case below which hides the dots - although does not fully meet your request.
Visually the goal is to allow the user to always view the outer paging limits

It certainly is possible to achieve what you are after however it would require code changes.
I'll mark this as an enhancement for now as others may enjoy a more compact paging scheme

---

```html
<!-- Example state which hides dots -->
<div paging
  page="3" 
  page-size="10" 
  total="50">
</div> 
```

![No Dot Example](https://cloud.githubusercontent.com/assets/1742101/10061854/b84b6e7e-622a-11e5-8e76-83daaa95344e.png)

**Comment by xxryan1234** [comment]
thanks @brantwills !

**Comment by brantwills** [comment]
Added granularity to show and hide first and last arrows
See release v2.1.0

**Comment by xxryan1234** [comment]
Thanks! Happy new year!
