### ISSUE TITLE
Paging with filter

### ISSUE THREAD

**Issue by PabloPG** [brantwills/Angular-Paging#30]
How to filter all list paginated?
When i use filter, only current page is filtered

```
<div class="row">
	<input type="text" ng-model="search" id="name">
	<label for="name">Search</label>
</div>
<div class="row">
	<pagination page="currentPage" page-size="pageSize" total="total"/>
	<ul class="collection">
		<li ng-repeat="mat in materiais | filter: search" class="collection-item">{{mat.name}}</li>
	</ul>
</div>
```

**Comment by optyler** [comment]
Well, your `filter` filters `<li>` elements while building the view, but your `$scope.materiais` array length is always the same with or without this filter and you `$scope.total` is alway the same too ;)

In my opinion, you should watch for your input[name] model changes with $watch and compute/update paginations variables ;)

**Comment by optyler** [comment]
Weeeeeel... that was not so simple as I thought ;)
You'll find here a demo : http://plnkr.co/4rhQzn

**Comment by PabloPG** [comment]
wow

Thx @optyler
