### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by xak2000** [brantwills/Angular-Paging#31]
I very like this component but want to suggest some visual improvements.
- Add `disabledClass` class to `...` as we cannot click on this and it should not change background-color on hover.
- Change `<span>` to `<a href="">` inside `<li>` for displaying "hand" pointer on hover. This also can be achieved by adding `cursor: pointer;` css rule to `<li>`. I prefer `a href` because it is specified in bootstrap's css and correctly removes hand pointer on currently active item.

**Comment by xak2000** [comment]
Another improvement can be more granularity for `show-prev-next`.
For example I want to show just `prev` and `next` buttons but without `first` and `last` buttons. Just as pagination on github.
Also it will be cool to have something like `label-prev`, `label-next`, `label-frirst` and `label-last` to change the text on these buttons. This can be useful for translations too.

Also it will be good to have someting like `tooltip-func` attribute to which callback function can be passed. This function receives the current buttons's page number and maybe additional params (like `paging-action`) and returns text which will be passed to `title` attribute. Something like `tooltip-func="GetCtrlPageTooltip(page, pageSize, total)"`.
In controller:
```
$scope.GetCtrlPageTooltip(page, pageSize, total) = function () {
  return 'Go to page number ' + page;
};
```

**Comment by brantwills** [comment]
Hey xak200 wow thank you so much for all the feedback!!

I will organize these into separate issues and then prioritize and tackle them one by one

It may take a moment, but I really like the ideas you have put forward, thank you again!!

**Comment by yacuzo** [comment]
From an accessibility point of view, it should be an <a> tag, or a button which is clicked. The <a> tag fits nicely with xak200's first point too.

**Comment by brantwills** [comment]
I've created unique issues for each item listed above
I will close out this issue and start working against issues 32 - 36
Feel free to continue commenting against this ticket if needed!

**Comment by xak2000** [comment]
I just realized you implemented all improvements! Just want to say thank you for all your good work! :+1:
