### ISSUE TITLE
No dependency on angular in bower.json

### ISSUE THREAD

**Issue by xak2000** [brantwills/Angular-Paging#43]
In `bower.json` file there is no `dependencies` section and `angular-paging` is not dependent on `angular`. But it is.

In my case I use `wiredep` plugin for `gulp` which sorts vendor js files based on their dependencies when concatenating and minifying them. Because it thinks that `angular-paging` is not dependent on `angular` it pasts it before angular in concatenated `vendor.js` file. And it doesn't work of course. It must be **after** angular because it uses `angular` for defining it's module.

So we need to add this:
```
      "dependencies": {
        "angular": "1.3+"
      }
```
to the `bower.json` file. (I don't know which angular version angular-paging is really need)

**Comment by brantwills** [comment]
Sounds good! I'll get this added into the next release probably targeting either the 1.3 or 1.2 version of angular.

**Comment by xak2000** [comment]
Ok, thanks! Now I'm using `overrides` section in my bower file for this. But it will be good if `angular-paging` will declare it's dependencies out of the box. :+1:

**Comment by brantwills** [comment]
Closed with version 2.2.0 release
