### ISSUE TITLE
is there a way to disabled paging-action programmatically ?

### ISSUE THREAD

**Issue by ekarudianto** [brantwills/Angular-Paging#44]
been using this component.. it's awesome component ! However, I've been wondering. is there a way to disabled the paging programmatically like if I put an attribute 

```javascript
$scope.disabled = true;

paging-disabled="disabled"
```

then the paging will be disabled till I put the $scope.disabled = false;

**Comment by brantwills** [comment]
Hey ekarudianto,

Right now there is no way to programmatically disable the directive, but that is not to say you could not wrap the component around, or even add, an ng-if / show / switch / etc.. statment to say show and hide the directive or something.

Sounds like you are interested in 'greying out' the entire paging list? Which is a pretty cool idea but one I may not implement immediately. I'll mark this as an enhancement for the time being.  Feel free to elaborate if this is not what you were thinking by disabled.

**Comment by Femina** [comment]
<div paging
    						page=curPage
    						page-size=pageSize
   						total=items.length
   						scroll-top="true"
					        show-prev-next="true"
			   		        class="pagination">
</div>

I am using your "paging directive" and in item_container I implemented as follows. ( curPage: 1, PageSize 18, Item count 11).
<div ng-repeat="data in items | paginate: curPage * pageSize | limitTo: pageSize">. But, I am not able to display items. I know i am missing to notice some minor thing. Thanks

**Comment by brantwills** [comment]
Hey Femina,

I am creating a new issue for you since your question does not involve disabling the paging directive programmatically.

**Comment by brantwills** [comment]
Closing this out as it is now implemented in the src files!
This update will be included in tag version 2.2.2
