### ISSUE TITLE
bower install angular-paging (fails)

### ISSUE THREAD

**Issue by jesben** [brantwills/Angular-Paging#46]
bower angular#1.5+        ENORESTARGET Tag/branch 1.5+ does not exist

**Comment by overbid** [comment]
This fix in last commit. (#557f3bfa71fe95adc55318a33c160800f8e80a4c)

**Comment by brantwills** [comment]
Thanks again guys - I'll tag this change into version 2.2.1 today - sorry for the delay!

**Comment by brantwills** [comment]
Alrighty, v2.2.1 published with the angular 1.5 version fix - closing out this issue
