### ISSUE TITLE
Adding the module declaration to the README/demo 

### ISSUE THREAD

**Issue by CariZa** [brantwills/Angular-Paging#47]
Hello,

Not an issue, just a suggestion.

Awesome plugin, very useful :) Just perhaps add something like this to the README (or wiki or demo) to make it easier to use:

> Add the Angular-Paging module as a dependency to your application module:
> 
> var app = angular.module('yourApp', ['bw.paging'])

I had to hunt through your source code for it.

**Comment by brantwills** [comment]
Genius! Will do as soon as possible
