### ISSUE TITLE
2.2.1 tag

### ISSUE THREAD

**Issue by Bazys** [brantwills/Angular-Paging#48]
please add 2.2.1 tag for bower

bower angular-paging#^2.2.1               ENORESTARGET No tag found that was able to satisfy ^2.2.1

Additional error details:
Available versions in git://github.com/brantwills/Angular-Paging.git: 2.2.0, 2.1.0, 2.0.0, 1.0.3, 1.0.2, 1.0.1, 1.0.0

**Comment by brantwills** [comment]
Hey Bazys, thanks I'll look into this - I noticed bower had not updated after I set the version on last bump.

**Comment by brantwills** [comment]
Ha! oops I updated the Changelog.txt file and completely forgot to tag the release

I've added the v2.2.1 release which seems to have updated bower appropriately
