### ISSUE TITLE
Did angular-paging really require angular 1.5+?

### ISSUE THREAD

**Issue by xak2000** [brantwills/Angular-Paging#50]
I ask because v2.1.0 works fine now with angular 1.4.10. And I can't upgrade to 1.5 yet. So can I upgrade angular-paging to v2.2.1? I look at commits and can't find any angular 1.5 features used. But `bower.json` declares `~1.5.0` now (which means 1.5+).

Maybe then we can set required angular version in bower json to: `>=1.4 <1.6` (or even `>=1.3 <1.6` if angular-paging works with angular 1.3).

**Comment by brantwills** [comment]
No we do not require angular 1.5+ 
I believe I was using 1.5 when the dependency was added and just included that version

I don't mind rolling back to a previous version
I'll keep this open for a bit in case anyone else out there has opinions on which version to select

I'll plan on updating the dependency to 1.3+ this weekend!
https://github.com/angular/angular.js/blob/master/CHANGELOG.md

**Comment by brantwills** [comment]
Updated both node and bower config to '>=1.3 <1.6'

Closing this out - keep me posted if this looks fishy!
