### ISSUE TITLE
reset paging to first

### ISSUE THREAD

**Issue by VincentHuang218** [brantwills/Angular-Paging#54]
Hi,
  It is the remoting data, when I paging to 5, then filting one field,the page-active also shown 5, how can i reset the paging to first?

**Comment by brantwills** [comment]
Hey VincentHuang218,

To better understand your issue I have created a plunker for us to work with:
http://plnkr.co/edit/2Alb1mL4n8GlZYSRYs6F?p=preview

Sounds like you are having an issue with the active page and resetting the paging directive.
When you have a moment could you try to reproduce your issue in the plunker?
This will allow me to view exactly what is happening and better troubleshoot.

Thanks!

**Comment by VincentHuang218** [comment]
Hey brantwills,

I am reading your directive code and already resolved the issue. thank you for your help.

**Comment by brantwills** [comment]
No problemo! 

Glad to hear you were able to solve the issue
