### ISSUE TITLE
Binding to scope variables

### ISSUE THREAD

**Issue by paulsperanza** [brantwills/Angular-Paging#57]
I have this html
`<paging page="1" page-size="12" total="{{pageResult.count}}" paging-action="pageChanged(page)"></paging>`

This in the controller
        $scope.pageResult = {
            count: 0,
            pageSize: 12,
            pageCount: 0,
            pages : [],
            currentPage: 1
        };

And I get this error
Syntax Error: Token '{' invalid key at column 2 of the expression [{{pageResult.count}}] starting at [{pageResult.count}}].

If I hard code a value for pageResult.count the pager works and my scope pageChanged funtion gets called. 

Is there something wrong with using scope variables?

**Comment by anteriovieira** [comment]
Try

``` html
total="pageResult.count"
```

**Comment by paulsperanza** [comment]
Thanks!
